### ISSUE TITLE
i am experiencing flickers while loading more data

### ISSUE THREAD

**Issue by jibraniqbal666** [mkrupal09/EasyAdapter#6]
I am using your library, when i add data using observable, screen flicker every time i use adapter.add(data) or adapter.addAll(data) usually 25 items., i think it is because of because because you are using ondatasetchange() on add data and notdatainserted or data range change., is there a hack or fix.

**Comment by mkrupal09** [comment]
you mean whenever you insert data to adapter it's refreshing recyclerview by notifydatasetchanged() in add() and addall() method. right?

**Comment by jibraniqbal666** [comment]
yes. because my data is images, i am using fresco, it is working great with my own adapter.

**Comment by mkrupal09** [comment]
fixed by adding addOnly() and removeOnly() method where you need to manually notify adapter
